### ISSUE TITLE
Installation fails (tried python 3.9 / 3.10)

### ISSUE THREAD

**Issue by Djoow** [ejba/pre-commit-maven#7]
Hello,
The installation of the plugin fails on MacOS using python3.9 or 3.10.

The log indicates that : 

> configuration error: `project` must contain ['name'] properties
          DESCRIPTION:
              Data structure for the **project** table inside ``pyproject.toml`` (as
              initially defined in :pep:`621`)
> ...
> ValueError: invalid pyproject.toml config: `project`

Have you already faced this kind of issue ?
Please let me know if you need further logs.

Regards,
Djow

**Comment by ejba** [comment]
Can you install the project again please?

**Comment by rieckpil** [comment]
I got the same issue and can confirm that with your recent change it works on my Mac (Apple MBP M1):

```
repos:
  - repo: https://github.com/ejba/pre-commit-maven
    rev: a7a66bd55c3d7b5c3083b7926753d0d48d17a498
    hooks:
      - id: maven
        args: ['-f somefolder/someproject/pom.xml spotless:apply']
```

I'm using Python 3.9.10
